name: Create or update Git reference
description: Create or update a Git reference (branch or tag) through GitHub API

branding:
  color: orange
  icon: git-branch

inputs:
  repository:
    description: The owner and repository name, in `owner/name` format
    default: ${{ github.repository }}
    required: true

  ref:
    description: Git reference to update or create (including `refs/heads/` or `refs/tags` prefix)
    default: ${{ github.ref }}
    required: true

  sha:
    description: Target commit SHA
    default: ${{ github.sha }}
    required: true

  force:
    description: Allow non-fast-forward updates (like `git push --force`)
    default: 'false'
    required: true

  github-token:
    description: GitHub API token to use
    default: ${{ github.token }}
    required: true

runs:
  using: node20
  main: dist/index.js
