name: Create or update Git reference
description: Create or update a Git reference (branch or tag) through GitHub API

inputs:
  repository:
    description: Repository name with owner
    default: ${{ github.repository }}
    required: true

  ref:
    description: Git ref to update or create
    default: ${{ github.ref }}
    required: true

  sha:
    description: Target commit SHA
    default: ${{ github.sha }}
    required: true

  force:
    description: Allow non-fast-forward updates
    default: 'false'
    required: true

  github-token:
    description: GitHub API token to use
    default: ${{ github.token }}
    required: true

runs:
  using: node20
  main: dist/index.js
