name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.node_id == github.event.pull_request.base.repo.node_id

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - id: rand
        run: echo "rand=$(openssl rand -hex 12)" >>"$GITHUB_OUTPUT"

      - id: create
        uses: ./.
        with:
          ref: refs/heads/testing/test-branch-${{ steps.rand.outputs.rand }}

      - run: git fetch origin testing/test-branch-${{ steps.rand.outputs.rand }}
      - run: test "$(git rev-parse FETCH_HEAD)" = "$GITHUB_SHA"

      - uses: ./.
        with:
          ref: refs/heads/testing/test-branch-${{ steps.rand.outputs.rand }}
          sha: 6a7b6624c39c94df7690a29f46b4abd5ce03b845
          force: true

      - run: git fetch origin testing/test-branch-${{ steps.rand.outputs.rand }}
      - run: test "$(git rev-parse FETCH_HEAD)" = "6a7b6624c39c94df7690a29f46b4abd5ce03b845"

      - uses: ./.
        with:
          ref: refs/heads/testing/test-branch-${{ steps.rand.outputs.rand }}

      - run: git fetch origin testing/test-branch-${{ steps.rand.outputs.rand }}
      - run: test "$(git rev-parse FETCH_HEAD)" = "$GITHUB_SHA"

      - uses: actions/github-script@v7
        if: always() && steps.create.outcome == 'success'
        with:
          script: |
            await github.request('DELETE /repos/{owner}/{repo}/git/refs/{ref}', {
              owner: process.env.GITHUB_REPOSITORY_OWNER,
              repo: process.env.GITHUB_REPOSITORY.split('/')[1],
              ref: `heads/testing/test-branch-${process.env.BRANCH_ID}`,
            });
        env:
          BRANCH_ID: ${{ steps.rand.outputs.rand }}
